import getRandomNumber from "../utils/getRandomNumber";

const gangNameList = {
  prefix: [
    "Southside",
    "Northside",
    "Eastside",
    "Westside",
    "12th Street",
    "18th Street",
    "Barrio",
    "Chinatown",
    "Downtown",
    "Uptown",
    "10th Avenue",
    "22nd Avenue",
    "Crazy Town",
    "East Coast",
    "West Coast",
    "Main Street",
    "Underground",
    "Hood",
    "The",
    "Dark",
    "Savage",
    "Wild",
    "Latin",
    "Ghost Town",
    "Los",
    "Humpty",
    "Notorious",
    "Cowbell",
    "Crazy",
    "Crusty",
    "Vegan",
    "Curmudgeonly",
    "Iron",
    "Saucy",
    "Good ol'",
    "Band of",
    "Big City",
    "Small Town",
    "Bloodthirsty",
    "Twisted",
    "River City",
    "Lake City",
    "Beachside",
    "Back Alley",
    "Country",
    "Dogtown",
    "Mystic",
    "Aztec",
    "Shadow",
    "Killer",
    "Infamous",
    "Battle",
    "War",
    "Road",
  ],
  suffix: [
    "Locos",
    "Clan",
    "Brotherhood",
    "Syndicate",
    "Ryders",
    "Family",
    "Familia",
    "Fancymen",
    "Clowns",
    "Cartel",
    "Mafia",
    "Boyz",
    "Nation",
    "Dawgz",
    "Jokerz",
    "Horsemen",
    "Militia",
    "Mob",
    "Gangstaz",
    "Hoodlums",
    "Crew",
    "Rapscallions",
    "Gang",
    "Scallywags",
    "Lunatics",
    "Ticklers",
    "Fiends",
    "Bruisers",
    "Hooligans",
    "Vermin",
    "Pirates",
    "Scumbags",
    "Sisterhood",
    "Warthogs",
    "Squad",
    "Soldiers",
    "Funnymen",
    "Animals",
    "Ladies Men",
    "Maids",
    "Poppers",
    "Homeslices",
    "Metalheads",
    "Ex-Girlfriends",
    "Ex-Boyfriends",
    "Zombies",
    "Lads",
    "Lords",
    "Triads",
    "Lunatics",
    "Warriors",
    "Butlers",
    "Maniacs",
    "Folk",
    "Nuns",
    "Saints",
  ],
};

const useNameGenerator = () => {
  const getRandomName = () => {
    return `${
      gangNameList.prefix[getRandomNumber(gangNameList.prefix.length)]
    } ${gangNameList.suffix[getRandomNumber(gangNameList.suffix.length)]}`;
  };

  return { getRandomName };
};

export default useNameGenerator;
